version: '3.8'
services:
  check-veracity:
    image: unga_bunga
    container_name: check-veracity
    build:
      context: .
    ports:
      - "8101:5000"
    command: ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]