apiVersion: v1
kind: Service
metadata:
  name: check-veracity-service
spec:
  selector:
    app: check-veracity
  ports:
    - protocol: TCP
      nodePort: 31313
      port: 8101  
      targetPort: 5000  
  type: NodePort  
